/**
 * Talent trees (FareverDB layout).
 * Per-column tier gates (root does not count): tier 1→0, 2→1, 3→3, 4→7.
 * From tier 2+: need ≥1 point in the cell(s) directly above.
 */

export const COLUMN_TIER_GATES = {
  1: 0,
  2: 1,
  3: 3,
  4: 7
};

/** @typedef {{ name: string, maxRank: number, description?: string }} TalentNodeDef */

/**
 * @type {Record<string, {
 *   root: TalentNodeDef,
 *   branches: TalentNodeDef[][]
 * }>}
 * branches[branchIndex][tierIndex] = nodes in that tier (left→right)
 */
export const TALENT_TREES = {
  Warrior: {
    root: {
      name: "Hemorrhage",
      maxRank: 1,
      description:
        "Your Physical Critical Strikes make the enemies bleed for 35% of the damage dealt over 8s."
    },
    branches: [
      [
        [{ name: "Seasoned Soldier", maxRank: 1 }],
        [
          { name: "Bloodletting", maxRank: 2 },
          { name: "Exsanguination", maxRank: 2 }
        ],
        [
          { name: "Master-at-arms", maxRank: 2 },
          { name: "Bruise", maxRank: 1 },
          { name: "Fighting Spirit", maxRank: 2 }
        ],
        [{ name: "Surge of Violence", maxRank: 1 }]
      ],
      [
        [{ name: "Sever", maxRank: 1 }],
        [
          { name: "Red Tempo", maxRank: 2 },
          {
            name: "Rash Soul",
            maxRank: 2,
            description: "Cooldown Reduction increased by 3% to 6%."
          }
        ],
        [
          { name: "Exposed Essence", maxRank: 2 },
          { name: "Cracking Blood", maxRank: 1 },
          { name: "Magic Conduction", maxRank: 2 }
        ],
        [{ name: "Infused Wound", maxRank: 1 }]
      ],
      [
        [{ name: "Rage Shield", maxRank: 1 }],
        [
          { name: "Bloodfeast", maxRank: 2 },
          { name: "Crippling Bloodloss", maxRank: 2 }
        ],
        [
          { name: "Hold the Line", maxRank: 2 },
          { name: "Shattered Rage", maxRank: 1 },
          { name: "Zealous Warrior", maxRank: 2 }
        ],
        [{ name: "Second Wind", maxRank: 1 }]
      ]
    ]
  },
  Mage: {
    root: {
      name: "Chaincast",
      maxRank: 1,
      description: "Using 4 Skills grants you Chaincast for 15s."
    },
    branches: [
      [
        [{ name: "Reverberate", maxRank: 1 }],
        [
          { name: "Concentrated Power", maxRank: 2 },
          { name: "Temporal Compression", maxRank: 2 }
        ],
        [
          { name: "Infinite Resources", maxRank: 1 },
          { name: "Prodigious Mind", maxRank: 2 },
          { name: "Expanded Spirit", maxRank: 2 }
        ],
        [{ name: "Conduit: Spark Explosion", maxRank: 1 }]
      ],
      [
        [{ name: "Discipline", maxRank: 1 }],
        [
          { name: "Chainstrike", maxRank: 2 },
          { name: "Nimble Fingers", maxRank: 2 }
        ],
        [
          { name: "Kinetic Surge", maxRank: 1 },
          { name: "Power Circuit", maxRank: 2 },
          { name: "Amplification", maxRank: 2 }
        ],
        [{ name: "High Voltage", maxRank: 1 }]
      ],
      [
        [{ name: "Conduit Residues", maxRank: 1 }],
        [
          { name: "Fervent Wizard", maxRank: 2 },
          { name: "Life Current", maxRank: 2 }
        ],
        [
          { name: "Echoing Life", maxRank: 1 },
          { name: "Spark Flask", maxRank: 2 },
          { name: "Flowing Vitality", maxRank: 2 }
        ],
        [{ name: "Conduit: Lifebolt", maxRank: 1 }]
      ]
    ]
  },
  Priest: {
    root: {
      name: "Sunlight",
      maxRank: 1,
      description:
        "Skills that affect allies empower them with Sunlight. The next Final Combo Attack consumes it for bonus damage."
    },
    branches: [
      [
        [{ name: "Soothing Rays", maxRank: 1 }],
        [
          { name: "Fervent Defender", maxRank: 2 },
          {
            name: "Crusader's Resolve",
            maxRank: 2,
            description:
              "Your Armor is increased by 4% to 8% and the threat generated by your Magic damage by 20%."
          }
        ],
        [
          { name: "Melting Faith", maxRank: 1 },
          { name: "Radiance", maxRank: 2 },
          { name: "Authority", maxRank: 2 }
        ],
        [{ name: "Luminous Bastion", maxRank: 1 }]
      ],
      [
        [{ name: "Purging Strikes", maxRank: 1 }],
        [
          { name: "Zealous Fighter", maxRank: 2 },
          { name: "Might of the Executioner", maxRank: 2 }
        ],
        [
          { name: "Potent Fortitude", maxRank: 1 },
          { name: "Prosecutor", maxRank: 2 },
          { name: "Pious Adept", maxRank: 2 }
        ],
        [{ name: "Solar Devotion", maxRank: 1 }]
      ],
      [
        [{ name: "Swift Justice", maxRank: 1 }],
        [
          { name: "Piercing Light", maxRank: 2 },
          { name: "Oppressive Rays", maxRank: 2 }
        ],
        [
          { name: "Burning Rays", maxRank: 1 },
          { name: "Sharp Mind", maxRank: 2 },
          { name: "Blessed Spirituality", maxRank: 2 }
        ],
        [{ name: "Sun Halo", maxRank: 1 }]
      ]
    ]
  },
  Rogue: {
    root: {
      name: "Lethal Poison",
      maxRank: 1,
      description:
        "Your Attacks have a 20% chance to apply a stack of Lethal Poison, poisoning them for 35% Dexterity Magic over 8s, stacking up to 5."
    },
    branches: [
      [
        [{ name: "Envenom", maxRank: 1 }],
        [
          { name: "Lethal Dose", maxRank: 2 },
          { name: "Finish the Job", maxRank: 2 }
        ],
        [
          { name: "Opportunity Strike", maxRank: 1 },
          { name: "Improved Mixture", maxRank: 2 },
          { name: "Deadly Poison", maxRank: 2 }
        ],
        [{ name: "Venomous Finisher", maxRank: 1 }]
      ],
      [
        [{ name: "Acidic Splatter", maxRank: 1 }],
        [
          { name: "Venom Infusion", maxRank: 2 },
          { name: "Up the Ante", maxRank: 2 }
        ],
        [
          { name: "Intent to Kill", maxRank: 1 },
          { name: "Noxious Stratagem", maxRank: 2 },
          { name: "Bullying the Weak", maxRank: 2 }
        ],
        [{ name: "Virulent Magic", maxRank: 1 }]
      ],
      [
        [{ name: "Adrenaline", maxRank: 1 }],
        [
          { name: "Footwork", maxRank: 2 },
          { name: "Leeching Poison", maxRank: 2 }
        ],
        [
          { name: "Crippling Poison", maxRank: 1 },
          { name: "Atrophic Poison", maxRank: 2 },
          { name: "Regenerating Miasmas", maxRank: 2 }
        ],
        [{ name: "Cheat Death", maxRank: 1 }]
      ]
    ]
  }
};

export function getTalentTree(className) {
  if (!className) {
    return null;
  }
  const key = Object.keys(TALENT_TREES).find(
    (name) => name.toLowerCase() === String(className).trim().toLowerCase()
  );
  return key ? TALENT_TREES[key] : null;
}
